version: "3"
services:
  api:
    container_name:  api-ox
    image:  ${API_IMAGE}
    ports:
      - 3333:3333
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - ox-networks
networks:
  ox-networks:
    