version: "3"
services:
  database:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    # platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ox-networks
    volumes:
      - ./.database:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s 
      retries: 5
    env_file:
      - ./.env
networks:
  ox-networks:
    
