version: "3"
services:
  web:
    container_name:  web-ox
    image:  ${WEB_IMAGE}
    ports:
      - 3000:3000
    environment:
      - CLIENT_ID_GOOGLE=${CLIENT_ID_GOOGLE}
      - CLIENT_SECRET_GOOGLE=${CLIENT_SECRET_GOOGLE}
      - CLIENT_ID_GITHUB=${CLIENT_ID_GITHUB}
      - CLIENT_SECRET_GITHUB=${CLIENT_SECRET_GITHUB}
      - SECRET_KEY=${SECRET_KEY}
      - NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL}
    networks:
      - ox-networks
networks:
  ox-networks:
    
